version: '3'
services:
  postgres:
   image: 'postgres:14.5'
   restart: always
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: movies
   logging:
     options:
       max-size: 10m
       max-file: "3"
   ports:
     - '5432:5432'
   volumes:
     - ./posgres-data:/var/lib/postgresql/data
     - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
   image: redis:latest
   restart: always
   ports:
      - "6379:6379"
   environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
   volumes:
      - ./redis-data:/root/redis